### Numpy basics

In [2]:
import numpy as np

#### Creating array from list

In [5]:
arr_1d = np.array([1,2,3,4,5])
print("1D array",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array:",arr_2d)

1D array [1 2 3 4 5]
2d array: [[1 2 3]
 [4 5 6]]


#### List vs numpy array

In [9]:
py_list = [1,2,3]
print("Python list multiplication",py_list*2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Python list multiplication",np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List opeartion time ",time.time()-start)

start = time.time()
np_array = np.arange(100000)*2
print("\n Numpy opeartion time ",time.time()-start)


Python list multiplication [1, 2, 3, 1, 2, 3]
Python list multiplication [2 4 6]

 List opeartion time  0.11173009872436523

 Numpy opeartion time  0.0


#### Creating array from scratch

In [13]:
zeros = np.zeros((4,5))
print("Zeros array:\n",zeros)

ones = np.ones((2,3))
print("one array: \n",ones)

full = np.full((2,2),7)
print("full array:\n",full)

random = np.random.random((2,3))
print("Random array: \n",random)

sequence = np.arange(0,11,2)
print("sequence array: \n",sequence)

Zeros array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
Random array: 
 [[0.22929087 0.08070945 0.41098998]
 [0.98625092 0.64086204 0.06977816]]
sequence array: 
 [ 0  2  4  6  8 10]


#### Vector , Matrices and Tensor

In [14]:
vector = np.array([1,2,3])
print("Vector",vector)

matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print("matrix",matrix)

tensor = np.array([[1,2],[3,4],
                   [5,6],[7,8]]) ## multidimensional array
print("tensor",tensor)

Vector [1 2 3]
matrix [[1 2 3]
 [4 5 6]]
tensor [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Array Properties

In [16]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape",arr.shape) #gives rows and columns
print("Dimension", arr.ndim)
print("size",arr.size) # No.of elemnets
print("DateType",arr.dtype)

Shape (2, 3)
Dimension 2
size 6
DateType int64


#### Array Reshaping

In [18]:
arr = np.arange(12)
print("Oriinal array",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array:",reshaped)

flattened = reshaped.flatten()
print("\n flattened array:",flattened)

#ravel ( returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array", raveled)

transpose = reshaped.T
print("\n Transposed array", transpose)

Oriinal array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
